### ISSUE TITLE
Help! Internet broken after trying this 

### ISSUE THREAD

**Issue by hgs54371** [jedisct1/bitbar-dnscrypt-proxy-switcher#3]
Please help, I can only use my phone right now

I opened bitbar and loaded this plug-in, switched to the dns proxy, but webpages are loading forever, 

Then I gave up and switch back to default, even close the app and remove the plug-in, 

But webpages Still not loading, After a restart, Everything shows no internet even the internet is indeed connected

Please help me resolve this, reset things to default, I can only use my phone right now

**Comment by usamabinattique** [comment]
you can reset your ethernet or wifi to default. if you ever run into network issues. 

To do this simply go to system preferences > network > click on the - button to delete whatever you're using. and then simply add that again and apply those changes.
