### ISSUE TITLE
Not working on macOS Catalina GM Release

### ISSUE THREAD

**Issue by welby12** [jedisct1/bitbar-dnscrypt-proxy-switcher#4]
I'm able to load other Bitbar plugins, but this one just has a "X" icon. 

Not sure if it has to do with all the new security features on Catalina in regards to the ~/Documents folder? 

Definitely not an execute permissions thing because if I do -x,  I get an entirely different icon when refreshing Bitbar (yellow exclamation). 

dnscrypt-proxy is running fine...

https://i.ibb.co/BVkmfDM/x-icon.png

**Comment by edhemphill** [comment]
Hi - check this article:
https://nektony.com/duplicate-finder-free/folders-permission

I had the same issue as you. To fix this I just moved my plugins folder out of ~/Documents and into a folder in my home directory. This fixed the issue. You can update the folder used for plugins in BitBar -> Preferences -> Change Plugin Folder
